### ISSUE TITLE
It is not an issue but a request

### ISSUE THREAD

**Issue by aman246149** [meetpatel0963/Online-judge#1]
can you make an article of this project it will be very helpful..

or for time being can you explain to me what is the use of **docker**  in this project..

also, can you explain to me what is your approach to writing run the sh file inside docker.

also please can you explain to me the 

judge.js and whole docker folder

**Comment by MeetPatel01** [comment]
Sure, I will make an article.

We used docker because if a user will send a python/java code to erase everything from the file system/directory (for ex. rm rf) then it may erase all the code files from the instance on which the user's code is running.

Using docker we ensure that even if a user executes something like that through the submitted program. it will affect that particular container only. In that case, we can throw an error and user can try submitting again without affecting the code files/project. The run.sh file contains the code to execute the programs in various programming languages. We are executing this file using docker run (i.e. inside docker container).

I will explain the details of judge.js and docker folder in the article/guide and will add it to this repo.

I hope this solves your questions.

**Comment by MeetPatel01** [comment]
Sure, I will make an article.

We used docker because if a user will send a python/java code to erase everything from the file system/directory (for ex. rm rf) then it may erase all the code files from the instance on which the user's code is running.

Using docker we ensure that even if a user executes something like that through the submitted program. it will affect that particular container only. In that case, we can throw an error and user can try submitting again without affecting the code files/project. The run.sh file contains the code to execute the programs in various programming languages. We are executing this file using docker run (i.e. inside docker container).

I will explain the details of judge.js and docker folder in the article/guide and will add it to this repo.

I hope this solves your questions.

**Comment by meetpatel0963** [comment]
Sure, I will make an article.

We used docker because if a user will send a python/java code to erase everything from the file system/directory (for ex. rm rf) then it may erase all the code files from the instance on which the user's code is running.

Using docker we ensure that even if a user executes something like that through the submitted program. it will affect that particular container only. In that case, we can throw an error and user can try submitting again without affecting the code files/project. The run.sh file contains the code to execute the programs in various programming languages. We are executing this file using docker run (i.e. inside docker container).

I will explain the details of judge.js and docker folder in the article/guide and will add it to this repo.

I hope this solves your questions.

**Comment by meetpatel0963** [comment]
Sure, I will make an article.

We used docker because if a user will send a python/java code to erase everything from the file system/directory (for ex. rm rf) then it may erase all the code files from the instance on which the user's code is running.

Using docker we ensure that even if a user executes something like that through the submitted program. it will affect that particular container only. In that case, we can throw an error and user can try submitting again without affecting the code files/project. The run.sh file contains the code to execute the programs in various programming languages. We are executing this file using docker run (i.e. inside docker container).

I will explain the details of judge.js and docker folder in the article/guide and will add it to this repo.

I hope this solves your queries.
